SET NOCOUNT ON;
SELECT 
    'CREATE TABLE ' + QUOTENAME(c.TABLE_SCHEMA) + '.' + QUOTENAME(c.TABLE_NAME) + ' (' + CHAR(13) + CHAR(10) +
    STRING_AGG(
        CAST('    ' + QUOTENAME(c.COLUMN_NAME) + ' ' + 
        c.DATA_TYPE + 
        CASE 
            WHEN c.DATA_TYPE IN ('varchar', 'nvarchar', 'char', 'nchar') THEN '(' + ISNULL(NULLIF(CAST(c.CHARACTER_MAXIMUM_LENGTH AS VARCHAR), '-1'), 'MAX') + ')' 
            WHEN c.DATA_TYPE IN ('decimal', 'numeric') THEN '(' + CAST(c.NUMERIC_PRECISION AS VARCHAR) + ',' + CAST(c.NUMERIC_SCALE AS VARCHAR) + ')' 
            ELSE '' 
        END + 
        CASE WHEN c.IS_NULLABLE = 'NO' THEN ' NOT NULL' ELSE ' NULL' END AS NVARCHAR(MAX)),
        ',' + CHAR(13) + CHAR(10)
    ) WITHIN GROUP (ORDER BY c.ORDINAL_POSITION) + CHAR(13) + CHAR(10) + ');' + CHAR(13) + CHAR(10) + 'GO' + CHAR(13) + CHAR(10)
FROM INFORMATION_SCHEMA.COLUMNS c
JOIN INFORMATION_SCHEMA.TABLES t ON c.TABLE_NAME = t.TABLE_NAME AND c.TABLE_SCHEMA = t.TABLE_SCHEMA
WHERE t.TABLE_TYPE = 'BASE TABLE'
GROUP BY c.TABLE_SCHEMA, c.TABLE_NAME;
