import React from 'react';
import { useNavigate } from 'react-router-dom';
import { History, ShieldCheck } from 'lucide-react';
import ReportShell, { TH, TD, fmt, todayISO, yearStartISO, PeriodControls } from './ReportShell';

// Map manual voucher type codes to the route that hosts VoucherEntry for that type.
// Auto-posted vouchers (SI, PV, PRV, SS, SSR) are opened on /vouchers/jv (generic view), since they
// were generated by their source documents — VoucherEntry treats them as view-only when Status !== Draft.
const TYPE_TO_ROUTE = {
    CPV: '/vouchers/cpv', CRV: '/vouchers/crv', BPV: '/vouchers/bpv',
    BRV: '/vouchers/brv', JV: '/vouchers/jv'
};

// ---- Voucher Audit Trail ----
export function VoucherAudit() {
    const navigate = useNavigate();
    const openVoucher = (v) => {
        const route = TYPE_TO_ROUTE[v.VoucherType] || '/vouchers/jv';
        navigate(`${route}?id=${v.VoucherID}`);
    };
    const statusBadge = (s) => {
        const bg = s === 'Posted' ? '#dcfce7' : s === 'Reversed' ? '#fee2e2' : '#f1f5f9';
        const col = s === 'Posted' ? '#15803d' : s === 'Reversed' ? '#b91c1c' : '#64748b';
        return <span style={{ background: bg, color: col, padding: '2px 8px', borderRadius: 99, fontSize: '0.7rem', fontWeight: 600 }}>{s}</span>;
    };
    return (
        <ReportShell
            title="Voucher Audit Trail"
            subtitle="All vouchers in a period (Posted, Reversed, Draft)."
            icon={History}
            endpoint="voucher-audit"
            defaultParams={{ from: yearStartISO(), to: todayISO() }}
            controls={({ params, updateParam }) => (
                <>
                    <select value={params.status || ''} onChange={e => updateParam('status', e.target.value || undefined)}
                        style={{ padding: '8px 12px', border: '1px solid #cbd5e1', borderRadius: 6, fontSize: '0.875rem' }}>
                        <option value="">All Statuses</option>
                        <option value="Posted">Posted</option>
                        <option value="Reversed">Reversed</option>
                        <option value="Draft">Draft</option>
                    </select>
                    <PeriodControls params={params} updateParam={updateParam} />
                </>
            )}
        >
            {(data) => (
                <>
                    <div className="card" style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
                        {Object.entries(data.counts).map(([s, c]) => (
                            <div key={s} style={{ background: '#f1f5f9', padding: '8px 12px', borderRadius: 6, fontSize: '0.85rem' }}>
                                <strong>{s}</strong>: {c}
                            </div>
                        ))}
                    </div>
                    <div className="card">
                        {data.rows.length === 0 ? (
                            <div style={{ padding: 24, color: '#64748b', textAlign: 'center' }}>No vouchers in this period.</div>
                        ) : (
                            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem' }}>
                                <thead>
                                    <tr style={{ background: '#f8fafc', borderBottom: '2px solid #e2e8f0' }}>
                                        <TH>Date</TH><TH>Voucher</TH><TH>Type</TH><TH>Status</TH>
                                        <TH>Source</TH><TH>Created By</TH><TH>Posted/Reversed</TH>
                                        <TH align="right">Amount</TH>
                                    </tr>
                                </thead>
                                <tbody>
                                    {data.rows.map(v => (
                                        <tr key={v.VoucherID}
                                            onClick={() => openVoucher(v)}
                                            style={{ borderBottom: '1px solid #f1f5f9', cursor: 'pointer' }}
                                            onMouseEnter={e => e.currentTarget.style.background = '#f8fafc'}
                                            onMouseLeave={e => e.currentTarget.style.background = 'transparent'}
                                        >
                                            <TD>{new Date(v.VoucherDate).toLocaleDateString()}</TD>
                                            <TD mono color="#475569">{v.VoucherNo}</TD>
                                            <TD>{v.VoucherType}</TD>
                                            <TD>{statusBadge(v.Status)}</TD>
                                            <TD>{v.SourceDocType ? `${v.SourceDocType} #${v.SourceDocID}` : '—'}</TD>
                                            <TD>{v.CreatedByName}</TD>
                                            <TD color="#64748b" >
                                                {v.Status === 'Reversed' && v.ReversedByName
                                                    ? `↩ ${v.ReversedByName} · ${v.ReversedAt ? new Date(v.ReversedAt).toLocaleDateString() : ''}`
                                                    : v.PostedAt ? new Date(v.PostedAt).toLocaleDateString() : '—'}
                                            </TD>
                                            <TD align="right" bold>{fmt(v.TotalAmount)}</TD>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        )}
                    </div>
                </>
            )}
        </ReportShell>
    );
}

// ---- System Account Reassignment Log ----
export function SystemAccountAudit() {
    return (
        <ReportShell
            title="System Account Reassignment Log"
            subtitle="Full history of system-role → COA account reassignments."
            icon={ShieldCheck}
            endpoint="system-account-audit"
            defaultParams={{}}
            controls={() => null}
        >
            {(data) => (
                <div className="card">
                    {data.rows.length === 0 ? (
                        <div style={{ padding: 24, color: '#64748b', textAlign: 'center' }}>No reassignments yet.</div>
                    ) : (
                        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem' }}>
                            <thead>
                                <tr style={{ background: '#f8fafc', borderBottom: '2px solid #e2e8f0' }}>
                                    <TH>When</TH><TH>Role</TH><TH>Old Account</TH><TH>New Account</TH>
                                    <TH>Reason</TH><TH>Changed By</TH>
                                </tr>
                            </thead>
                            <tbody>
                                {data.rows.map(r => (
                                    <tr key={r.AuditID} style={{ borderBottom: '1px solid #f1f5f9' }}>
                                        <TD>{new Date(r.ChangedAt).toLocaleString()}</TD>
                                        <TD bold mono>{r.RoleKey}</TD>
                                        <TD color="#64748b">
                                            {r.OldGLCode ? `${r.OldGLCode} — ${r.OldGLTitle}` : <em>none</em>}
                                        </TD>
                                        <TD>
                                            <strong>{r.NewGLCode}</strong> — {r.NewGLTitle}
                                        </TD>
                                        <TD color="#475569">{r.Reason || '—'}</TD>
                                        <TD>{r.ChangedByName}</TD>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    )}
                </div>
            )}
        </ReportShell>
    );
}
