const MODULES = [
    { key: 'workshop_customers',  label: 'Workshop Customers',   section: 'WORKSHOP & SERVICE' },
    { key: 'workshop_jobs',       label: 'Job Cards',            section: 'WORKSHOP & SERVICE' },
    { key: 'workshop_labour',     label: 'Labour & Services',    section: 'WORKSHOP & SERVICE' },
    { key: 'workshop_sublet',     label: 'Sublet Repairs',       section: 'WORKSHOP & SERVICE' },
    { key: 'workshop_parts_issue',label: 'Parts Issue',          section: 'WORKSHOP & SERVICE' },
    { key: 'workshop_settings',      label: 'Workshop Settings',    section: 'WORKSHOP & SERVICE' },
    { key: 'workshop_careoff',       label: 'Care-Off Management',  section: 'WORKSHOP & SERVICE' },
    { key: 'workshop_accessories',   label: 'Accessories Admin',    section: 'WORKSHOP & SERVICE' },
    { key: 'workshop_controller',    label: 'Job Controller',        section: 'WORKSHOP & SERVICE' },
    { key: 'workshop_gatepass',      label: 'Gate Pass',             section: 'WORKSHOP & SERVICE' },
    { key: 'parts_spare',         label: 'Spare Parts',          section: 'PARTS & INVENTORY' },
    { key: 'procurement_grn',     label: 'Receiving (GRN)',      section: 'PARTS & INVENTORY' },
    { key: 'procurement_grtn',    label: 'Returns (GRTN)',       section: 'PARTS & INVENTORY' },
    { key: 'sales_store',         label: 'Store Sale (Spares)',  section: 'PARTS & INVENTORY' },
    { key: 'sales_ssr',           label: 'Sale Returns (SSR)',   section: 'PARTS & INVENTORY' },
    { key: 'inventory_settings',  label: 'Parts Config',         section: 'PARTS & INVENTORY' },
    { key: 'finance_coa',         label: 'Chart of Accounts',    section: 'FINANCE & ACCOUNTS' },
    { key: 'finance_vouchers',    label: 'Vouchers (CPV/CRV/BPV/BRV/JV)', section: 'FINANCE & ACCOUNTS' },
    { key: 'accounting_setup',    label: 'Accounting Setup',     section: 'FINANCE & ACCOUNTS' },
    { key: 'payments',            label: 'Receive / Make Payment', section: 'FINANCE & ACCOUNTS' },
    { key: 'finance_cheques',     label: 'Cheque Clearance',       section: 'FINANCE & ACCOUNTS' },
    { key: 'reports',             label: 'Financial Reports',      section: 'FINANCE & ACCOUNTS' },
    { key: 'crm_parties',         label: 'Credit Parties',       section: 'ACCOUNTS & CRM' },
    { key: 'crm_party_access',    label: 'Party Business Access', section: 'ACCOUNTS & CRM' },
    { key: 'crd_followups',       label: 'CRD Follow-Ups',       section: 'ACCOUNTS & CRM' },
    { key: 'cro_workspace',       label: 'CRO Workspace',         section: 'CUSTOMER RELATION' },
    { key: 'cro_admin',           label: 'CRO Admin (rules, templates, system roles)', section: 'CUSTOMER RELATION' },
    { key: 'cro_dept_responder',  label: 'CRO Department Responder', section: 'CUSTOMER RELATION' },
    { key: 'cro_reports',         label: 'CRO Reports',           section: 'CUSTOMER RELATION' },
    // Sales module — locked decision #2, #14, #20, #22 referenced in .claude/planning/sales-module-design.md §2
    { key: 'sales_executive',       label: 'Sales Executive (booking, payments, docs)', section: 'NEW VEHICLE SALES' },
    { key: 'sales_agm',             label: 'Sales AGM (team view + assign inquiries)',   section: 'NEW VEHICLE SALES' },
    { key: 'sales_gm',              label: 'Sales GM (full team + targets + policies)',  section: 'NEW VEHICLE SALES' },
    { key: 'sales_admin_pricing',   label: 'Sales — Pricing Admin (approve discounts)',  section: 'NEW VEHICLE SALES' },
    { key: 'sales_admin_settings',  label: 'Sales — Catalog & Policy Admin',             section: 'NEW VEHICLE SALES' },
    { key: 'sales_master_settlement', label: 'Sales — Master Invoice Posting',           section: 'NEW VEHICLE SALES' },
    { key: 'sales_recovery',        label: 'Sales — Recovery Officer',                   section: 'NEW VEHICLE SALES' },
    { key: 'sales_reports',         label: 'Sales Reports',                              section: 'NEW VEHICLE SALES' },
    { key: 'sales_hierarchy',       label: 'Sales Hierarchy & Targets (HR-side)',        section: 'ADMIN & HR' },
    { key: 'hr_employees',        label: 'Employees',            section: 'ADMIN & HR' },
    { key: 'hr_settings',         label: 'HR Config',            section: 'ADMIN & HR' },
    { key: 'admin_users',         label: 'User Management',        section: 'ADMINISTRATION' },
    { key: 'admin_permissions',   label: 'Role Permissions',       section: 'ADMINISTRATION' },
    { key: 'finalize',            label: 'Finalize Records',        section: 'WORKFLOW' },
    { key: 'am_approve',          label: 'Approve Unfinalize (AM)', section: 'WORKFLOW' },
    { key: 'admin_unfinalize',    label: 'Perform Unfinalize',      section: 'WORKFLOW' },
];

module.exports = MODULES;
